### ISSUE TITLE
Controlling the package loaded LightGBM library

### ISSUE THREAD

**Issue by wakakusa** [IQVIA-ML/LightGBM.jl#64]
Is it possible to control the LightGBM library to be read by the package by specifying the directory where the LightGBM library is located with the LIGHTGBM_PATH environment variable so that the LightGBM compiled from the source code can be used?

**Comment by yalwan-iqvia** [comment]
Hi @wakakusa !

Unfortunately, it is not currently possible (I stripped it down to the simplest possible thing). As an immediate workaround, you can remove the downloaded `lib_lightgbm.so` from the julia package path and put a symlink to your own, but I will explore options to make it so that you can supply your own library. Bear in mind I want to avoid introducing custom environment variables so anything I would do to enable this would center around placing `lib_lightgbm.so` into linkable library path (such as LD_LIBRARY_PATH on UNIX systems).

**Comment by iqml** [comment]
We need to ensure we come up with a platform-neutral solution.

**Comment by yalwan-iqvia** [comment]
Hi @wakakusa -- was the request motivated by the new release of LightGBM 3.0.0? We would want to look into making sure the wrapper supports this version of the library as well (#65)

**Comment by wakakusa** [comment]
Hi @yalwan-iqvia ,There are two reasons.
First, I'd like to try out the new release of LightGBM (3.0. 0).
The other one seems not to work with LightGBM, which provides some of the parameters such as device specification. Therefore, you need to make use of LightGBM built from source.

**Comment by yalwan-iqvia** [comment]
Hi @wakakusa 

I just wanted to draw your attention to the fact that LGBM V3 support was released (v0.4.0). We had to update the internal API to support this so this feature would not have helped here. We're also about to upgrade the package to 3.1.0 with a release coming soon. But also we have some plans to work soon on letting user supply own binary.

**Comment by chilledgeek** [comment]
Hi @wakakusa we've implemented the logic to use custom `lib_lightgbm` binaries now.

You can refer to https://github.com/IQVIA-ML/LightGBM.jl#custom-lightgbm-binaries on how to set this up.

Thanks!

**Comment by wakakusa** [comment]
Hi  @chilledgeek 
Thank you for implementing the logic using the custom lib _ lightgbm binary!!
I will use it right away.
