### ISSUE TITLE
Warning or default for when no metrics set for cv?

### ISSUE THREAD

**Issue by chilledgeek** [IQVIA-ML/LightGBM.jl#83]
I noticed that when an estimator has the flag `is_training_metric = true` but no metrics set, the cv returns an empty object without warning (see example below).

This might be nothing (as expected), but I thought I'd just raise it to see whether this should be allowed, or whether we should either have a warning saying no metrics specified, or set some default metric if none is specified?

```
# Arrange
train_matrix = rand(1000,70) # create random dataset
train_labels = rand([0, 1], 1000)
splits = (collect(1:200), collect(201:400), collect(401:600), collect(601:800), collect(801:1000))
estimator = LightGBM.LGBMClassification(
    objective = "binary",
    num_class = 1,
    is_training_metric = true
    # metric = ["auc"] ### NOT SET!!!
)

# Act
output = LightGBM.cv(estimator, train_matrix, train_labels, splits, verbosity = -1)

# Check
output
# prints out this...which is empty
# Dict{String,Dict{String,Array{Float64,1}}}()
```

**Comment by yalwan-iqvia** [comment]
Given LightGBM proper permits this without spewing any additional warnings I'm not sure we want to do too much extra. I think one of the philosophies we want to try to stick to is being the thinnest wrapper possible (without being inconvenient to use, hence some of the higher level functions).

**Comment by kainkad** [comment]
I came across this issue while working on another task so it's not too outdated and I think this behaviour can be changed.  The empty cv output in this case occurs because of the default metric for LGBMClassification is currently set to “None” on LightGBM.jl side. As per LightGBM [documentation](https://lightgbm.readthedocs.io/en/v3.3.5/Parameters.html#metric) this results in no metric being registered. However, the default behaviour seem to rather be with the metric set to an empty string `“”` which means that the metric corresponding to specified objective will be for the pre-defined objective functions only, otherwise no metric will be used. So changing this default with your example would be like this:

```

using LightGBM

# Arrange
train_matrix = rand(1000,70) # create random dataset
train_labels = rand([0, 1], 1000)
splits = (collect(1:200), collect(201:400), collect(401:600), collect(601:800), collect(801:1000))
estimator = LightGBM.LGBMClassification(
    objective = "binary",
    num_class = 1,
    is_training_metric = true,
    metric  = [""]
)

# Act
output = LightGBM.cv(estimator, train_matrix, train_labels, splits, verbosity = -1)

# Check
output
# prints out:
# Dict{String, Dict{String, Vector{Float64}}} with 2 entries:
  # "validation" => Dict("binary_logloss"=>[0.700103, 0.702722, 0.695875, 0.69976, 0.696504])
  # "training"   => Dict("binary_logloss"=>[0.654497, 0.667058, 0.666231, 0.671141, 0.672454])

```
Looking back at the code, it used to be like that where there were separate estimators for binary and multiclass each with their own default metrics matching the LightGBM documentation (so with `binary_logloss` for binary objective and `multi_logloss`  for multiclass). Then, a change was made to have one estimator instead that can be used for both binary and multiclass and its default was set to “None” (ref: https://github.com/IQVIA-ML/LightGBM.jl/pull/31).
I think it does make sense to set that metric back to use the corresponding defaults based on the objective so I have created a small PR #151 and then your example would work when no metric is specified and return the `binary_logloss` in the cv output.
However, since I don’t know the context for the change made on the MLJInterface (https://github.com/IQVIA-ML/LightGBM.jl/blob/master/src/MLJInterface.jl#L167) and wouldn’t want to have a breaking change in that default, I only updated the core LGBMClassification and left the default to "None" for MLJ classifier. It can always be changed if needed.
